version: "3.8"

services:
  cpp_dev:
    container_name: cpp21_debug_container
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
